name: BlockRacing
version: 4.0
main: cf.fhshkl.blockracing.Main
api-version: 1.21
authors: [ LQ_Snow, xiaojiuwo233, FHSHKL ]
description: Collect target blocks to win
commands:
  skill:
    usage: "/skill <skillName>"
    description: "try buy skill"
  chest:
    usage: "/chest <chestId>"
    description: "open team chest"
  waypoint:
    usage: "/waypoint [rm|use] <waypointId>"
    description: "rm/use waypoint"
  locate:
    usage: "/locatestruct [structure|biome] <structure|biome>"
    description: "locate structure/biome"
  menu:
    usage: "/menu"
    description: "open menu"
  team:
    usage: "/team"
    description: "open join team menu"
  tp:
    usage: "/tp <playerName>"
    description: "teleport between teammate"

